// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {store} from '../models';
import {model} from '../models';

export function BinaryName():Promise<string>;

export function CheckForUpdates():Promise<update.Info>;

export function ClaudeConfig():Promise<string>;

export function ClaudeConfigForProject(arg1:string):Promise<string>;

export function ClearLogs():Promise<void>;

export function CreateProject(arg1:store.ProjectInput):Promise<model.Project>;

export function CreateSkill(arg1:store.SkillInput):Promise<model.Skill>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate():Promise<string>;

export function GetDBPath():Promise<string>;

export function GetLogs(arg1:number):Promise<Array<string>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSkill(arg1:string):Promise<model.Skill>;

export function GetSkillByID(arg1:string):Promise<model.Skill>;

export function ListProjects():Promise<Array<model.Project>>;

export function ListSkills():Promise<Array<model.Skill>>;

export function LogPath():Promise<string>;

export function MCPStatus():Promise<Record<string, any>>;

export function MCPToolsPreview():Promise<string>;

export function MoveSkill(arg1:string,arg2:string,arg3:string):Promise<model.Skill>;

export function NormalizeName(arg1:string):Promise<string>;

export function NormalizeSlug(arg1:string):Promise<string>;

export function OpenReleasePage(arg1:string):Promise<string>;

export function OpencodeConfig():Promise<string>;

export function OpencodeConfigForProject(arg1:string):Promise<string>;

export function ProjectMCPToolsPreview(arg1:string):Promise<string>;

export function ProjectSkillCount(arg1:string):Promise<number>;

export function ReorderSkills(arg1:Array<string>):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetSkillEnabled(arg1:string,arg2:boolean):Promise<model.Skill>;

export function SkipUpdateVersion(arg1:string):Promise<void>;

export function StartMCP():Promise<string>;

export function StorePath():Promise<string>;

export function TestMCP():Promise<string>;

export function TestProjectMCP(arg1:string):Promise<string>;

export function UpdateProject(arg1:string,arg2:store.ProjectInput):Promise<model.Project>;

export function UpdateSkill(arg1:string,arg2:store.SkillInput):Promise<model.Skill>;

export function Version():Promise<string>;
