// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BinaryName() {
  return window['go']['main']['App']['BinaryName']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClaudeConfig() {
  return window['go']['main']['App']['ClaudeConfig']();
}

export function ClaudeConfigForProject(arg1) {
  return window['go']['main']['App']['ClaudeConfigForProject'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateSkill(arg1) {
  return window['go']['main']['App']['CreateSkill'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DownloadAndInstallUpdate() {
  return window['go']['main']['App']['DownloadAndInstallUpdate']();
}

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkill(arg1) {
  return window['go']['main']['App']['GetSkill'](arg1);
}

export function GetSkillByID(arg1) {
  return window['go']['main']['App']['GetSkillByID'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function LogPath() {
  return window['go']['main']['App']['LogPath']();
}

export function MCPStatus() {
  return window['go']['main']['App']['MCPStatus']();
}

export function MCPToolsPreview() {
  return window['go']['main']['App']['MCPToolsPreview']();
}

export function MoveSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveSkill'](arg1, arg2, arg3);
}

export function NormalizeName(arg1) {
  return window['go']['main']['App']['NormalizeName'](arg1);
}

export function NormalizeSlug(arg1) {
  return window['go']['main']['App']['NormalizeSlug'](arg1);
}

export function OpenReleasePage(arg1) {
  return window['go']['main']['App']['OpenReleasePage'](arg1);
}

export function OpencodeConfig() {
  return window['go']['main']['App']['OpencodeConfig']();
}

export function OpencodeConfigForProject(arg1) {
  return window['go']['main']['App']['OpencodeConfigForProject'](arg1);
}

export function ProjectMCPToolsPreview(arg1) {
  return window['go']['main']['App']['ProjectMCPToolsPreview'](arg1);
}

export function ProjectSkillCount(arg1) {
  return window['go']['main']['App']['ProjectSkillCount'](arg1);
}

export function ReorderSkills(arg1) {
  return window['go']['main']['App']['ReorderSkills'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SetSkillEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetSkillEnabled'](arg1, arg2);
}

export function SkipUpdateVersion(arg1) {
  return window['go']['main']['App']['SkipUpdateVersion'](arg1);
}

export function StartMCP() {
  return window['go']['main']['App']['StartMCP']();
}

export function StorePath() {
  return window['go']['main']['App']['StorePath']();
}

export function TestMCP() {
  return window['go']['main']['App']['TestMCP']();
}

export function TestProjectMCP(arg1) {
  return window['go']['main']['App']['TestProjectMCP'](arg1);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}

export function UpdateSkill(arg1, arg2) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
