// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {model} from '../models';
import {store} from '../models';
import {gitsync} from '../models';

export function BinaryName():Promise<string>;

export function CheckForUpdates():Promise<update.Info>;

export function ClaudeConfig():Promise<string>;

export function ClaudeConfigControl():Promise<string>;

export function ClaudeConfigForProject(arg1:string):Promise<string>;

export function ClaudeConfigForProjectIn(arg1:string,arg2:string):Promise<string>;

export function ClaudeConfigForWorkspace(arg1:string):Promise<string>;

export function ClearLogs():Promise<void>;

export function CloneWorkspace(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<model.Workspace>;

export function ControlMCPToolsPreview():Promise<string>;

export function CreateProject(arg1:store.ProjectInput):Promise<model.Project>;

export function CreateSkill(arg1:store.SkillInput):Promise<model.Skill>;

export function CreateWorkspace(arg1:store.WorkspaceInput):Promise<model.Workspace>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate():Promise<string>;

export function ExportArchive(arg1:string,arg2:string,arg3:string):Promise<Record<string, string>>;

export function GetDBPath():Promise<string>;

export function GetLogs(arg1:number):Promise<Array<string>>;

export function GetMainWorkspace():Promise<model.Workspace>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSkill(arg1:string):Promise<model.Skill>;

export function GetSkillByID(arg1:string):Promise<model.Skill>;

export function GetWorkspaceConflicts(arg1:string):Promise<gitsync.ConflictsResult>;

export function ImportArchive(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function ListProjects():Promise<Array<model.Project>>;

export function ListProjectsIn(arg1:string):Promise<Array<model.Project>>;

export function ListSkills():Promise<Array<model.Skill>>;

export function ListSkillsIn(arg1:string):Promise<Array<model.Skill>>;

export function ListWorkspaces():Promise<Array<model.Workspace>>;

export function LogPath():Promise<string>;

export function MCPStatus():Promise<Record<string, any>>;

export function MCPToolsPreview():Promise<string>;

export function MoveSkill(arg1:string,arg2:string,arg3:string):Promise<model.Skill>;

export function MoveSkillTo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.Skill>;

export function NormalizeName(arg1:string):Promise<string>;

export function NormalizeSlug(arg1:string):Promise<string>;

export function OpenCheckoutEditor(arg1:string):Promise<void>;

export function OpenCheckoutFile(arg1:string,arg2:string):Promise<void>;

export function OpenCheckoutFolder(arg1:string):Promise<void>;

export function OpenCheckoutTerminal(arg1:string):Promise<void>;

export function OpenReleasePage(arg1:string):Promise<string>;

export function OpencodeConfig():Promise<string>;

export function OpencodeConfigControl():Promise<string>;

export function OpencodeConfigForProject(arg1:string):Promise<string>;

export function OpencodeConfigForProjectIn(arg1:string,arg2:string):Promise<string>;

export function OpencodeConfigForWorkspace(arg1:string):Promise<string>;

export function ProjectMCPToolsPreview(arg1:string):Promise<string>;

export function ProjectMCPToolsPreviewIn(arg1:string,arg2:string):Promise<string>;

export function ProjectSkillCount(arg1:string):Promise<number>;

export function PullWorkspace(arg1:string):Promise<Record<string, any>>;

export function PushWorkspace(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function ReorderSkills(arg1:Array<string>):Promise<void>;

export function ResetWorkspace(arg1:string):Promise<Record<string, any>>;

export function ResolveWorkspaceConflicts(arg1:string,arg2:gitsync.ResolveRequest):Promise<gitsync.ResolveResult>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetSkillEnabled(arg1:string,arg2:boolean):Promise<model.Skill>;

export function SetWorkspaceGit(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.Workspace>;

export function SkipUpdateVersion(arg1:string):Promise<void>;

export function StartMCP():Promise<string>;

export function StorePath():Promise<string>;

export function TestControlMCP():Promise<string>;

export function TestMCP():Promise<string>;

export function TestProjectMCP(arg1:string):Promise<string>;

export function TestProjectMCPIn(arg1:string,arg2:string):Promise<string>;

export function TestWorkspaceMCP(arg1:string):Promise<string>;

export function UpdateProject(arg1:string,arg2:store.ProjectInput):Promise<model.Project>;

export function UpdateSkill(arg1:string,arg2:store.SkillInput):Promise<model.Skill>;

export function UpdateWorkspace(arg1:string,arg2:store.WorkspaceInput):Promise<model.Workspace>;

export function Version():Promise<string>;

export function WorkspaceCheckoutDir(arg1:string):Promise<string>;

export function WorkspaceGitStatus(arg1:string):Promise<string>;

export function WorkspaceMCPToolsPreview(arg1:string):Promise<string>;

export function WorkspaceSkillCount(arg1:string):Promise<number>;
